/*
 * This file was generated by Guardrail (https://github.com/twilio/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
*/
package com.example.guardrailspringdemo.definitions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;
import static java.util.Objects.requireNonNull;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Category {

    @JsonProperty("id")
    private final Optional<Long> id;

    @JsonProperty("name")
    private final Optional<String> name;

    @JsonCreator
    protected Category(@JsonProperty("id") final Optional<Long> id, @JsonProperty("name") final Optional<String> name) {
        super();
        this.id = id == null ? Optional.empty() : id;
        this.name = name == null ? Optional.empty() : name;
    }

    public Optional<Long> getId() {
        return this.id;
    }

    public Optional<String> getName() {
        return this.name;
    }

    @Override
    public String toString() {
        return "Category{" + "id=" + getId() + ", name=" + getName() + "}";
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final Category other = (Category) o;
        return getId().equals(other.getId()) && getName().equals(other.getName());
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(getId(), getName());
    }

    public static class Builder {

        private Optional<Long> id = Optional.empty();

        private Optional<String> name = Optional.empty();

        public Builder() {
        }

        public Builder(final Category template) {
            this.id = template.getId();
            this.name = template.getName();
        }

        public Builder withId(final long id) {
            this.id = Optional.of(id);
            return this;
        }

        public Builder withId(final Optional<Long> optionalId) {
            this.id = requireNonNull(optionalId, "optionalId is required");
            return this;
        }

        public Builder withName(final String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        public Builder withName(final Optional<String> optionalName) {
            this.name = requireNonNull(optionalName, "optionalName is required");
            return this;
        }

        public Category build() {
            requireNonNull(this.id, "this.id is required");
            requireNonNull(this.name, "this.name is required");
            return new Category(this.id, this.name);
        }
    }
}
