/*
 * This file was generated by Guardrail (https://github.com/twilio/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
*/
package com.example.guardrailspringdemo.definitions;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Optional;
import static java.util.Objects.requireNonNull;
import com.fasterxml.jackson.annotation.JsonValue;
import com.example.guardrailspringdemo.Shower;

public enum PetStatus {

    AVAILABLE("available"), PENDING("pending"), SOLD("sold");

    static {
        Shower.getInstance().register(PetStatus.class, PetStatus::getName);
    }

    private final String name;

    private PetStatus(final String name) {
        this.name = name;
    }

    @JsonValue
    public String getName() {
        return this.name;
    }

    @JsonCreator
    public static PetStatus parse(final String name) {
        for (final PetStatus value : values()) {
            if (value.name.equals(name))
                return value;
        }
        throw new IllegalArgumentException("Name '" + name + "' is not valid for enum 'PetStatus'");
    }
}
