/*
 * This file was generated by Guardrail (https://github.com/twilio/guardrail).
 * Modifications will be overwritten; instead edit the OpenAPI/Swagger spec file.
*/
package com.example.guardrailspringdemo.pet;

import java.util.Optional;
import java.util.concurrent.CompletionStage;
import javax.validation.constraints.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.async.DeferredResult;
import org.springframework.web.multipart.MultipartFile;
import com.example.guardrailspringdemo.*;
import com.example.guardrailspringdemo.definitions.*;

public interface PetHandler {

    abstract class AddPetResponse {

        private final int statusCode;

        AddPetResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class Created extends AddPetResponse {

            private Created() {
                super(201);
            }
        }

        public static class BadRequest extends AddPetResponse {

            private BadRequest() {
                super(400);
            }
        }

        public static final Created Created = new Created();

        public static final BadRequest BadRequest = new BadRequest();
    }

    abstract class UpdatePetResponse {

        private final int statusCode;

        UpdatePetResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class BadRequest extends UpdatePetResponse {

            private BadRequest() {
                super(400);
            }
        }

        public static class NotFound extends UpdatePetResponse {

            private NotFound() {
                super(404);
            }
        }

        public static final BadRequest BadRequest = new BadRequest();

        public static final NotFound NotFound = new NotFound();
    }

    abstract class FindPetsByStatusResponse {

        private final int statusCode;

        FindPetsByStatusResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class Ok extends FindPetsByStatusResponse {

            private final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody;

            private Ok(final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody) {
                super(200);
                this.entityBody = entityBody;
            }

            public java.util.List<com.example.guardrailspringdemo.definitions.Pet> getEntityBody() {
                return this.entityBody;
            }
        }

        public static class BadRequest extends FindPetsByStatusResponse {

            private BadRequest() {
                super(400);
            }
        }

        public static class NotFound extends FindPetsByStatusResponse {

            private NotFound() {
                super(404);
            }
        }

        public static final BadRequest BadRequest = new BadRequest();

        public static final NotFound NotFound = new NotFound();

        public static Ok Ok(final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody) {
            return new Ok(entityBody);
        }
    }

    abstract class FindPetsByStatusEnumResponse {

        private final int statusCode;

        FindPetsByStatusEnumResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class Ok extends FindPetsByStatusEnumResponse {

            private final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody;

            private Ok(final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody) {
                super(200);
                this.entityBody = entityBody;
            }

            public java.util.List<com.example.guardrailspringdemo.definitions.Pet> getEntityBody() {
                return this.entityBody;
            }
        }

        public static class BadRequest extends FindPetsByStatusEnumResponse {

            private BadRequest() {
                super(400);
            }
        }

        public static final BadRequest BadRequest = new BadRequest();

        public static Ok Ok(final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody) {
            return new Ok(entityBody);
        }
    }

    abstract class FindPetsByTagsResponse {

        private final int statusCode;

        FindPetsByTagsResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class Ok extends FindPetsByTagsResponse {

            private final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody;

            private Ok(final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody) {
                super(200);
                this.entityBody = entityBody;
            }

            public java.util.List<com.example.guardrailspringdemo.definitions.Pet> getEntityBody() {
                return this.entityBody;
            }
        }

        public static class BadRequest extends FindPetsByTagsResponse {

            private BadRequest() {
                super(400);
            }
        }

        public static final BadRequest BadRequest = new BadRequest();

        public static Ok Ok(final java.util.List<com.example.guardrailspringdemo.definitions.Pet> entityBody) {
            return new Ok(entityBody);
        }
    }

    abstract class UpdatePetWithFormResponse {

        private final int statusCode;

        UpdatePetWithFormResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class BadRequest extends UpdatePetWithFormResponse {

            private BadRequest() {
                super(400);
            }
        }

        public static final BadRequest BadRequest = new BadRequest();
    }

    abstract class GetPetByIdResponse {

        private final int statusCode;

        GetPetByIdResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class Ok extends GetPetByIdResponse {

            private final com.example.guardrailspringdemo.definitions.Pet entityBody;

            private Ok(final com.example.guardrailspringdemo.definitions.Pet entityBody) {
                super(200);
                this.entityBody = entityBody;
            }

            public com.example.guardrailspringdemo.definitions.Pet getEntityBody() {
                return this.entityBody;
            }
        }

        public static class BadRequest extends GetPetByIdResponse {

            private BadRequest() {
                super(400);
            }
        }

        public static class NotFound extends GetPetByIdResponse {

            private NotFound() {
                super(404);
            }
        }

        public static final BadRequest BadRequest = new BadRequest();

        public static final NotFound NotFound = new NotFound();

        public static Ok Ok(final com.example.guardrailspringdemo.definitions.Pet entityBody) {
            return new Ok(entityBody);
        }
    }

    abstract class DeletePetResponse {

        private final int statusCode;

        DeletePetResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class Ok extends DeletePetResponse {

            private Ok() {
                super(200);
            }
        }

        public static class BadRequest extends DeletePetResponse {

            private BadRequest() {
                super(400);
            }
        }

        public static class NotFound extends DeletePetResponse {

            private NotFound() {
                super(404);
            }
        }

        public static final Ok Ok = new Ok();

        public static final BadRequest BadRequest = new BadRequest();

        public static final NotFound NotFound = new NotFound();
    }

    abstract class UploadFileResponse {

        private final int statusCode;

        UploadFileResponse(final int statusCode) {
            this.statusCode = statusCode;
        }

        public int getStatusCode() {
            return this.statusCode;
        }

        public static class Ok extends UploadFileResponse {

            private final com.example.guardrailspringdemo.definitions.ApiResponse entityBody;

            private Ok(final com.example.guardrailspringdemo.definitions.ApiResponse entityBody) {
                super(200);
                this.entityBody = entityBody;
            }

            public com.example.guardrailspringdemo.definitions.ApiResponse getEntityBody() {
                return this.entityBody;
            }
        }

        public static Ok Ok(final com.example.guardrailspringdemo.definitions.ApiResponse entityBody) {
            return new Ok(entityBody);
        }
    }

    CompletionStage<PetHandler.AddPetResponse> addPet(final com.example.guardrailspringdemo.definitions.Pet body);

    CompletionStage<PetHandler.UpdatePetResponse> updatePet(final com.example.guardrailspringdemo.definitions.Pet body);

    CompletionStage<PetHandler.FindPetsByStatusResponse> findPetsByStatus(final java.util.List<String> status);

    CompletionStage<PetHandler.FindPetsByStatusEnumResponse> findPetsByStatusEnum(final String status);

    CompletionStage<PetHandler.FindPetsByTagsResponse> findPetsByTags(final java.util.List<String> tags);

    CompletionStage<PetHandler.UpdatePetWithFormResponse> updatePetWithForm(final long petId,
            final java.util.Optional<String> name, final java.util.Optional<String> status);

    CompletionStage<PetHandler.GetPetByIdResponse> getPetById(final long petId);

    CompletionStage<PetHandler.DeletePetResponse> deletePet(final long petId, final java.util.Optional<String> apiKey,
            final java.util.Optional<Boolean> includeChildren, final java.util.Optional<String> status);

    CompletionStage<PetHandler.UploadFileResponse> uploadFile(final long petId,
            final java.util.Optional<String> additionalMetadata, final java.util.Optional<MultipartFile> file,
            final MultipartFile file2, final MultipartFile file3, final long longValue, final long customValue,
            final java.util.Optional<Long> customOptionalValue);
}
